- hosts: default
  connection: local
  gather_facts: no
  vars_files: 
    - ../vars/main.yml # not required. The directory name from which the variables should be loaded.,If the path is relative, it will look for the file in vars/ subdirectory of a role or relative to playbook.
  tasks:
    - name: home brew tap
      homebrew_tap:
          name: "{{item}}" # required. The GitHub user/organization repository to tap.
          state: present # not required. choices: present;absent. state of the repository.
      with_items: "{{brew_taps}}"
    - name: home brew casks
      homebrew_cask:
          name: "{{item}}" # required. The GitHub user/organization repository to tap.
          install_options: "appdir=/Applications" # not required. options flags to install a package
          # upgrade: yes # not required. upgrade all casks (mutually exclusive with `upgrade`)
          accept_external_apps: yes # not required. allow external apps
          # greedy: yes # not required. upgrade casks that auto update; passes --greedy to brew cask outdated when checking if an installed cask has a newer version available
          state: present # not required. choices: present;absent. state of the repository.
      with_items: "{{brew_cask_apps}}"    
    - name: home brew packages 
      homebrew:
          state: present # not required. choices: head;latest;present;absent;linked;unlinked. state of the package
          name: "{{brew_packages}}" # not required. list of names of packages to install/remove