- hosts: default
  connection: local
  gather_facts: no
  # sudo: yes
  vars_files:
      - ../../../group_vars/local/main.yml # not required. The directory name from which the variables should be loaded.,If the path is relative, it will look for the file in vars/ subdirectory of a role or relative to playbook
  tasks:
    - name: check zprezto exists
      stat:
          path: "{{ local_home}}/.zprezto" # required. The full path of the file/object to get the facts of.
      register: zprezto
    - name: install zprezto
      git:
          dest: "{{ local_home}}/.zprezto" # required. The path of where the repository should be checked out. This parameter is required, unless C(clone) is set to C(no).
          repo: https://github.com/sorin-ionescu/prezto.git  # required. git, SSH, or HTTP(S) protocol address of the git repository.
          recursive: yes # not required. if C(no), repository will be cloned without the --recursive option, skipping sub-modules.
      when: zprezto.stat.exists == false
    - name: setup zprezto
      shell: |
        setopt EXTENDED_GLOB 
        for rcfile in "{{local_home}}"/.zprezto/runcoms/^README.md(.N); do
          ln -s "${rcfile}" "{{local_home}}"/."${rcfile:t}"
        done
      args:
          creates: "{{local_home}}/.zshrc" # not required. a filename, when it already exists, this step will B(not) be run.
          chdir: "{{local_home}}" # not required. cd into this directory before running the command
          executable: /usr/local/bin/zsh # not required. change the shell used to execute the command. Should be an absolute path to the executable.
    - name: zshrc set up
      copy:
          dest: "{{local_home}}/.zshrc" # required. Remote absolute path where the file should be copied to. If I(src) is a directory, this must be a directory too. If I(dest) is a nonexistent path and if either I(dest) ends with "/" or I(src) is a directory, I(dest) is created. If I(src) and I(dest) are files, the parent directory of I(dest) isn't created: the task fails if it doesn't already exist.
          src: ../files/.zshrc # not required. Local path to a file to copy to the remote server; can be absolute or relative. If path is a directory, it is copied recursively. In this case, if path ends with "/", only inside contents of that directory are copied to destination. Otherwise, if it does not end with "/", the directory itself with all contents is copied. This behavior is similar to Rsync.
          force: yes # not required. the default is C(yes), which will replace the remote file when contents are different than the source. If C(no), the file will only be transferred if the destination does not exist.
    - name: init zsh
      shell: source ~/.zshrc
      args:
        executable: /usr/local/bin/zsh # not required. change the shell used to execute the command. Should be an absolute path to the executable