# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ("$SHLVL" -eq 1 && ! -o LOGIN) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export PATH="/usr/local/opt/mysql@5.7/bin:$PATH"
export PATH=~/.local/bin:$PATH
export PATH=$PATH:$GOPATH/bin
export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
export NVM_DIR="$HOME/.nvm"
export GOPATH=${HOME}/go
export GO111MODULE=on
# export PATH=$PATH:$(npm bin -g)
export GOENV_ROOT=$HOME/.goenv
export PATH=$GOENV_ROOT/bin:$PATH
export PATH=$GOPATH/bin:$PATH
export GOENV_DISABLE_GOPATH=1
